### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by nodwan** [oxinon/IOTA-price-ticker-V2-TTGO-T-Display#1]
later install the screen is always black. in serial console ... all is ok. 

the board is TTGO 19-6-28 V1.1 XY-CP

**Comment by oxinon** [comment]
couldn't find your board on TTGO, which board is that exactly? Have you also selected your board in ~ / Arduino / libraries / eTFT_eSPI / User_Setup_Select.h ?

**Comment by nodwan** [comment]
Hi, thanks for your Replay, 

here 2 pictures of the board ... what i have to change in User_Setup_Select ??





Gesendet von myMail für iOS


Montag, 4. Januar 2021, 11:00 +0100 von notifications@github.com  <notifications@github.com>:

**Comment by oxinon** [comment]
Here are a old video from beginn, to install the libs and config. Please note you are using the new coinmarketcap and new ArduinoJason, this is not show in this old video.
https://drive.google.com/file/d/1Ga2iJM3Ak_gisMH6_qPQO0_A-FekmS0v/view?usp=sharing

**Comment by oxinon** [comment]
read discription
