### ISSUE TITLE
[SOLVED]  deserializeJson() failed: NoMemory

### ISSUE THREAD

**Issue by dl8ebd** [oxinon/IOTA-price-ticker-V2-TTGO-T-Display#2]
Hello,
after the Bitcoin ticker worked without any problems for quite a while, I've been getting the following message in the serial monitor for a few days now:

_Getting ticker data for BTC
/v1/cryptocurrency/quotes/latest?symbol=BTC&convert=EUR
.... connected to server
deserializeJson() failed: NoMemory
Error getting data: NoMemory_

in my opinion it can not be due to pro.coinmarketcap.com. 
I see my accesses....

Any idea?

Thanks
Thomas

**Comment by tonyharney** [comment]
I'm getting the same _NoMemory_ error, but can see that I'm connecting to coinmarketcap and my credits are increasing from the API pulls from their site.

**Comment by oxinon** [comment]
Thanks for the info, I'll try to see what the problem is.

**Comment by dl8ebd** [comment]
Hi oxinon,
the problem persists - is there a solution yet?
thanks
Thomas

**Comment by dl8ebd** [comment]
I see you are no longer interested in the project.
Waste of time...

**Comment by oxinon** [comment]
I found the problem, it's with the Coinmarketcap library. Open this file with Notepad++ or another editor /Arduino/libraries/CoinMarketCapApi2/scr/CoinMarketCapApi.ccp

go to line 76 and change the setting from 2048 to 3072
DynamicJsonDocument doc (3072);

Then save, recompile and flash.

**Comment by dl8ebd** [comment]
great!
I test it later this evening and give you a feedback

EDIT:  PROBLEM SOLVED
works perfekt!
Many thanks for your help
